### ISSUE TITLE
2023.3.1 support

### ISSUE THREAD

**Issue by pderiy** [EnzDev/idea-ngx-translate-autocomplete#170]
The plugin works with JetBrains products up to version `2023.2`.
Version `2023.3.1` is currently not supported.

**Comment by wolanskiadrian** [comment]
Any progress on that?

**Comment by jtmmsg** [comment]
It says "Incompatible: requires IDE build 232.* or earlier". But the current build is "Build #IU-233.13135.103, built on December 20, 2023". Can you please support the current version?

**Comment by EnzDev** [comment]
Yea sorry, I'm a bit burnt out.
I'm updating the plugin currently, it should be on the marketplace in a couple of days.

**Comment by jtmmsg** [comment]
Sorry to hear that - thank you and get well soon!

**Comment by MrFiregore** [comment]
if you need help I can help you

**Comment by EnzDev** [comment]
You can now check for updates in IntelliJ, the plugin has been validated and is available in the market place :smile: 
Thanks @MrFiregore ! Don't hesitate to contact me, my info are available on my profile.
