### ISSUE TITLE
Version support

### ISSUE THREAD

**Issue by Khaldor48** [EnzDev/idea-ngx-translate-autocomplete#216]
![image](https://github.com/user-attachments/assets/41ef2d55-42e8-47be-8a81-cc2feb492469)

Hello, I am using your plugin and it's brilliant. Could you please make it compatible with newer version of WebStorm? 
Thank you in advance :)

**Comment by MrFiregore** [comment]
pls

**Comment by Minecraftschurli** [comment]
I have opened a PR (#217)

**Comment by EnzDev** [comment]
Hello, thanks to @Minecraftschurli a version for the latest versions of IntelliJ is now available on the marketplace 🙂
