### ISSUE TITLE
[FEATURE-REQUEST] inline blame a like 

### ISSUE THREAD

**Issue by AsimNet** [EnzDev/idea-ngx-translate-autocomplete#7]
Hey @EnzDev 
Thank you for the plugin. I'm really impressed by the work you did. It makes the development experience much much easier. Especially with huge HTML files!

Is it possible to add a feature like a `git inline blame` plugin?
![git inline blame](https://user-images.githubusercontent.com/3624441/131338315-0afdc267-4a90-4571-983d-2499fb7893bb.png)
(git inline blame)
And as a WebStomr user, I should choose the preferred language shown next to the current line.

Thank you.

**Comment by EnzDev** [comment]
Hi ! Thank you for giving a chance to my plugin :smile: 
If I understand correctly, you would want to have the translation in your preferred language displayed at the end of the line like git inline blame does ?

I'm currently developing something similar but inplace of the translation like Java Properties, e.g.

Reopening a file ![image](https://user-images.githubusercontent.com/14039086/131537391-11d9b546-ee3c-42a9-908a-87891c7e40bd.png)
 
Hover ![image](https://user-images.githubusercontent.com/14039086/131537478-3e8fb251-76da-42a0-a6e7-dc53444613b9.png)

On click ![image](https://user-images.githubusercontent.com/14039086/131538341-d46ea368-19db-400b-bfd9-a940a31fc04d.png)

**Comment by EnzDev** [comment]
This feature will also include actions to modify a translation and rename (with refactoring) the key.

**Comment by EnzDev** [comment]
See #11 & #12
