### ISSUE TITLE
Is it possible to add several directories?

### ISSUE THREAD

**Issue by ParsaArvanehPA** [EnzDev/idea-ngx-translate-autocomplete#84]
### Discussed in https://github.com/EnzDev/idea-ngx-translate-autocomplete/discussions/80

<div type='discussions-op-text'>

<sup>Originally posted by **ParsaArvanehPA** August 16, 2022</sup>
Hi,
I was wondering is it possible to add several directories containing json files?
The project I'm working on is made of more than 10 application, and each have their own i18n directory.</div>

**Comment by EnzDev** [comment]
Hi, will add/rework when I find more time next year.
