### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by IAPBenediktZwoelfer** [EnzDev/idea-ngx-translate-autocomplete#97]
Intellij Crashes when opening Settings.. -> Tools -> NgTranslate Toolset

"Build #IU-221.5921.22, built on June 21, 2022"

Crash log:

Cannot create configurable

com.intellij.diagnostic.PluginException: Cannot load class fr.enzomallard.ngxtranslatetoolset.configuration.NgTranslateToolsetConfigurable (
  error: fr/enzomallard/ngxtranslatetoolset/configuration/NgTranslateToolsetConfigurable has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=NgTranslate Toolset, id=com.github.enzdev.ideangxtranslateautocomplete, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\idea-ngx-translate-autocomplete, version=0.1.3, package=null, isBundled=false), packagePrefix=null, instanceId=356, state=active)
)

**Comment by EnzDev** [comment]
Hello, I'm sorry but the last version was marked compatible with older version of Intellij, I've fixed the compatibility matrix :)
